# Change these first
owner: pi4li
repo: statuspage # The name of this repository

sites:
  - name: PI4LI Website
    url: https://pi4li.com
  - name: Assets Server
    url: https://assets.pi4li.com
  - name: NatAndruStudy
    url: https://natandrustudy.com
  - name: GymDays
    url: https://gymdays.co.uk
  - name: Where Have I Been?
    url: https://wherehaveibeen.co.uk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pi4li.com
  # baseUrl: /your-repo-name
  favicon: https://assets.pi4li.com/favicon.ico
  logoUrl: https://assets.pi4li.com/logos/pi4li/pi4lilogo.svg
  name: PI4LI
  introTitle: "Keep up-to-date with the current status of PI4LI projects!"
  introMessage: This status page is automatically updated every time we have an issue and is updated by us during every incident.
  navbar:
    - title: Status
      href: /
    - title: Back to PI4LI
      href: https://pi4li.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
#
